### ISSUE TITLE
\BiteAWX\core.py Error

### ISSUE THREAD

**Issue by luobu-code** [Mo-Dabao/BiteAWX#1]
>>> from BiteAWX import AWX

Traceback (most recent call last):

  File "d:\anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-9108c7af918b>", line 1, in <module>
    from BiteAWX import AWX

  File "d:\anaconda\lib\site-packages\BiteAWX\__init__.py", line 8, in <module>
    from BiteAWX.core import AWX

  File "d:\anaconda\lib\site-packages\BiteAWX\core.py", line 97
    if p := col_length:
          ^
SyntaxError: invalid syntax

**Comment by luobu-code** [comment]
only >=Python 3.8  ok ?

**Comment by Mo-Dabao** [comment]
是的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Mo-Dabao/BiteAWX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月12日(星期天) 晚上6:34
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [Mo-Dabao/BiteAWX] \BiteAWX\core.py Error (Issue #1)





 
only &gt;=Python 3.8  ok ?

**Comment by luobu-code** [comment]
thank u
